"""make review.content not null

Revision ID: 42dbf9eae91f
Revises: 6dad12365842
Create Date: 2025-05-16 19:13:08.011915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42dbf9eae91f'
down_revision: Union[str, None] = '6dad12365842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
