"""Init db migration

Revision ID: 6dad12365842
Revises: 
Create Date: 2025-05-16 19:08:48.542093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dad12365842'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashPwd', sa.String(), nullable=False),
    sa.Column('public_reviews', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movie',
    sa.Column('tconst', sa.Text(), nullable=False),
    sa.Column('primaryTitle', sa.Text(), nullable=True),
    sa.Column('originalTitle', sa.Text(), nullable=True),
    sa.Column('Poster_Link', sa.Text(), nullable=True),
    sa.Column('startYear', sa.Integer(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('Certificate', sa.Text(), nullable=True),
    sa.Column('runtimeMinutes', sa.Integer(), nullable=True),
    sa.Column('Director', sa.Text(), nullable=True),
    sa.Column('Star1', sa.Text(), nullable=True),
    sa.Column('Star2', sa.Text(), nullable=True),
    sa.Column('Star3', sa.Text(), nullable=True),
    sa.Column('Star4', sa.Text(), nullable=True),
    sa.Column('Overview', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('roles',
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('analytics_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.Column('viewer_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_username'], ['member.username'], ),
    sa.ForeignKeyConstraint(['viewer_username'], ['member.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.tconst'], ),
    sa.ForeignKeyConstraint(['username'], ['member.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(), nullable=False),
    sa.Column('viewer_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_username'], ['member.username'], ),
    sa.ForeignKeyConstraint(['viewer_username'], ['member.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.role'], ),
    sa.ForeignKeyConstraint(['username'], ['member.username'], ),
    sa.PrimaryKeyConstraint('username', 'role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('review_share')
    op.drop_table('review')
    op.drop_table('analytics_share')
    op.drop_table('roles')
    op.drop_table('movie')
    op.drop_table('member')
    # ### end Alembic commands ###
